name: learn-github-actions
on:
  label:
    types:
      - edited
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
